[build]
  publish = "."
  
[[redirects]]
  from = "/aplicaciones/calculadora-fertilidad/*"
  to = "/aplicaciones/calculadora-fertilidad-app/:splat"
  status = 200

[[redirects]]
  from = "/calculadora-fertilidad"
  to = "/aplicaciones/calculadora-fertilidad-app/index.html"
  status = 200

[[redirects]]
  from = "/calculadora-fertilidad/*"
  to = "/aplicaciones/calculadora-fertilidad-app/:splat"
  status = 200

[[redirects]]
  from = "/calculadora-riesgo-aborto"
  to = "/aplicaciones/calculadora-riesgo-aborto/index.html"
  status = 200

[[redirects]]
  from = "/calculadora-riesgo-aborto/*"
  to = "/aplicaciones/calculadora-riesgo-aborto/:splat"
  status = 200

[[redirects]]
  from = "/dosvidas"
  to = "/aplicaciones/DosVidas/index.html"
  status = 200

[[redirects]]
  from = "/dosvidas/*"
  to = "/aplicaciones/DosVidas/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
